const notAvailableBrands = [
  "ACCENT",
  "Achosa",
  "AG Green",
  "Alena Goretskaya",
  "Almila-Lux",
  "Almirastyle",
  "Anli",
  "AnnLine",
  "Arisha",
  "Art Oliya",
  "Avenue Fashion",
  "Avila",
  "AVLINE",
  "BELAN textile",
  "Belarusachka",
  "Bell Bimbo",
  "Bliss",
  "Bonadi",
  "Bright Style",
  "Bugalux",
  "BUNABOUTIQUE",
  "Cherire",
  "Chumakova Fashion",
  "Claire",
  "Conte Elegant",
  "Cool Flax",
  "Elod",
  "ElPaiz",
  "EV&ES",
  "Faldas",
  "Faufilure",
  "Faufilure outlet",
  "Gallant Touch",
  "Garsonnier",
  "IL GATTO",
  "Imperata",
  "Individual design",
  "La Prima",
  "La rouge",
  "La Stella",
  "Lady Smile",
  "Lady Style Classic",
  "LadyThreeStars",
  "LaVeLa",
  "Le Collect",
  "Le Rina",
  "Legend Style",
  "Lejole",
  "Lenta OUTLET",
  "Leorgofman",
  "LindaLux",
  "Lisse Lingerie",
  "Lucky mum",
  "LucyCo",
  "LULA.BY",
  "LUXTEX",
  "Ma Vie",
  "MadameRita",
  "Madech",
  "MAL'KO",
  "MALKOVICH",
  "Mamma Moda",
  "Manklover",
  "MARIKA",
  "MEDIUM",
  "Melissena",
  "Mido",
  "Milla Jo",
  "MilMil",
  "MIRSINA FASHION",
  "Mita",
  "Moveri by Larisa Balunova",
  "N.A.B. clothes",
  "Nadex",
  "Nalina",
  "Nat Max",
  "Natali Tushinskaya",
  "Nelva",
  "Nivard",
  "OLANTIZ",
  "One by Morozov",
  "Ouarida",
  "Pama Style",
  "Papilio Kids",
  "PATRICIA by La Cafe",
  "Pavlova",
  "R.O.S.E.",
  "R&B",
  "Rawwwr clothing",
  "Romgil",
  "Rosheli",
  "Rujena",
  "S. Veles",
  "S.O.L O Me",
  "Saffonov",
  "Shetti",
  "Shymoda",
  "Sisters Solonko",
  "Souffle",
  "SOVA",
  "SUNITSA",
  "SVETLANA GNEDENOK",
  "Tanya Arzhanova",
  "Teyli",
  "Totallook",
  "TrendCorner",
  "TSURAN",
  "Velona",
  "Verally",
  "VEXUS`S",
  "Weaver",
  "Winkler’s World",
  "Купалинка",
  "Ружана",
  "Слонимская ФХИ",
]

module.exports = {
  notAvailableBrands,
};
